language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
services:
  - postgresql

script:
  - "mvn clean verify"
  - zip si-project-artifact.zip target/si-projekt-anamnese-service-0.0.1-SNAPSHOT.jar
  - mkdir -p dpl_cd_upload
  - mv si-project-artifact.zip dpl_cd_upload/si-project-artifact.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on:
      branch: issue-65-Connect_backend_with_RDS_in_aws
      repo: "SI-Projekt/SI-Projekt-Anamnese-Service"
    bucket: si-project-anamnesis-bucket
    region: us-east-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: si-project-anamnesis-bucket
    key: si-project-artifact.zip
    bundle_type: zip
    application: si-projekt-anamnese_service
    deployment_group: si-projekt-deployment_group_name
    region: us-east-1
    wait_until_deployed: true
    on:
      branch: issue-65-Connect_backend_with_RDS_in_aws
      repo: "SI-Projekt/SI-Projekt-Anamnese-Service"
