language: java
sudo: false
jdk:
- openjdk8
cache:
directories:
  - $HOME/.m2
maven_build:
stage: build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on:
      branch: &master
    bucket: si-project-bucket
    region: us-east-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: si-project-bucket
    key: latest.jar
    bundle_type: jar
    application: si-projekt-anamnese-service
    deployment_group: si-projekt-deployment_group_name
    region: us-east-1
    on:
      branch: *master

script:
    - mvn clean verify
    - mkdir -p dpl_cd_upload
    - mv target/si-projekt-anamnese-service-0.0.1-SNAPSHOT.jar dpl_cd_upload/latest.jar
