language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
script:
  #- "mvn clean package -Djava.awt.headless=true"
  - "mvn clean verify"
  - mkdir -p dpl_cd_upload
  - mv target/si-projekt-anamnese-service-0.0.1-SNAPSHOT.jar dpl_cd_upload/si-projekt-anamnese-service-0.0.1-SNAPSHOT.jar

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on:
      branch: issue-65-Connect_backend_with_RDS_in_aws
      repo: "SI-Projekt/SI-Projekt-Anamnese-Service"
    bucket: si-project-anamnesis-bucket
    region: us-east-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: si-project-anamnesis-bucket
    key: si-projekt-anamnese-service-0.0.1-SNAPSHOT.jar
    bundle_type: jar
    application: si-projekt-anamnese-service
    deployment_group: si-projekt-deployment_group_name
    region: us-east-1
    on:
      branch: issue-65-Connect_backend_with_RDS_in_aws
      repo: "SI-Projekt/SI-Projekt-Anamnese-Service"