version: 0.0
os: linux
files:
  - source: ./target/si-projekt-anamnese-service-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stopapp.sh
  BeforeInstall:
    - location: scripts/utilities.sh
  AfterInstall:
    - location: scripts/set-env.sh
  ApplicationStart:
    - location: scripts/startappsilent.sh
