package thb.siprojektanamneseservice.model;


public enum AllergyType {
    ANTIBIOTIKA,
    FRUCHTZUCKER,
    NAHRUNGSMITTEL,
    POLLEN,
    ROENTGENKONTRASTMITTEL,
    TIERHAAR,
    LOKALANAESTHETIKA,
    MILCHZUCKER,
    HAUSSTAUB,
    KONSERVIERUNGSSTOFFE,
    VITAMIN_B;
}
